version: '3.9'
services:
  webserver:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: webserver
    volumes:
      - ./app:/var/www
    ports:
      - "8080:80"
    depends_on:
      - mysql
  cronjob:
    container_name: cronjob
    build:
      context: .
      dockerfile: Dockerfile
      target: cronjob
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
      - webserver
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: